name: twilio_programmable_video_web
description: A web implementation of the Twilio Programmable Video Plugin.
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues
version: 1.2.0

environment:
  sdk: '>=3.3.0-0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  twilio_programmable_video_platform_interface:
    git:
      url: https://github.com/martintrollip/programmable-video.git
      path: programmable_video_platform_interface
      ref: 1.2.0
  js: ^0.6.3
  enum_to_string: ^2.0.1
  dartlin: ^0.6.1
  version: ^2.0.0
  collection: ^1.15.0

# Comment for local testing
dependency_overrides:
  twilio_programmable_video_platform_interface:
    path: ../programmable_video_platform_interface

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ProgrammableVideoPlugin
        fileName: twilio_programmable_video_web.dart
