name: twilio_programmable_video_web
description: A web implementation of the Twilio Programmable Video Plugin.
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues
version: 1.3.1

environment:
  sdk: '>=3.3.0-0 <4.0.0'
  flutter: '>=3.19.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  twilio_programmable_video_platform_interface:
    git:
      url: https://github.com/martintrollip/programmable-video.git
      path: programmable_video_platform_interface
      ref: 1.3.1
  js: ^0.6.4
  enum_to_string: ^2.0.1
  dartlin: ^0.6.3
  version: ^3.0.2
  collection: ^1.18.0

## uncomment for local dev
#dependency_overrides:
#  twilio_programmable_video_platform_interface:
#    path: ../programmable_video_platform_interface

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ProgrammableVideoPlugin
        fileName: twilio_programmable_video_web.dart
