name: twilio_programmable_video_example
description: Demonstrates how to use the twilio_programmable_video plugin.
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.3.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^4.7.3
  rxdart: ^0.27.7
  provider: ^5.0.0
  native_device_orientation: ^1.2.1
  enum_to_string: ^2.0.1
  recase: ^4.1.0
  intl: ^0.19.0
  device_info: ^2.0.3
  wakelock_plus: ^1.2.4
  after_layout: ^1.2.0
  uuid: ^3.0.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  collection: ^1.18.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  twilio_programmable_video:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true