name: twilio_programmable_video
description: Flutter plugin for Twilio Programmable Video, which enables you to build real-time videocall applications (WebRTC)
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1 
  enum_to_string: ^2.0.1
  twilio_programmable_video_platform_interface:
    git:
      url: https://github.com/martintrollip/programmable-video.git
      path: programmable_video_platform_interface
      ref: main
  twilio_programmable_video_web: 
    git:
      url: https://github.com/martintrollip/programmable-video.git
      path: programmable_video_web
      ref: main
  collection: ^1.15.0

# For local testing
#
# Replace above with twilio_programmable_video_platform_interface: any
#
# dependency_overrides:
#   twilio_programmable_video_platform_interface:
#     path: ../programmable_video_platform_interface
#   twilio_programmable_video_web:
#     path: ../programmable_video_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.6
  build_runner: ^2.0.1
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_programmable_video
        pluginClass: TwilioProgrammableVideoPlugin
      ios:
        pluginClass: TwilioProgrammableVideoPlugin
      web:
        default_package: twilio_programmable_video_web
