name: twilio_programmable_video
description: Flutter plugin for Twilio Programmable Video, which enables you to build real-time videocall applications (WebRTC)
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues
version: 1.3.4

environment:
  sdk: '>=3.3.0-0 <4.0.0'
  flutter: '>=3.19.3'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1 
  enum_to_string: ^2.0.1
  twilio_programmable_video_platform_interface:
    git:
      url: https://github.com/martintrollip/programmable-video.git
      path: programmable_video_platform_interface
      ref: 1.3.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.0.1
  flutter_lints: ^4.0.0

# uncomment for local dev
#dependency_overrides:
#  twilio_programmable_video_platform_interface:
#    path: ../programmable_video_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_programmable_video
        pluginClass: TwilioProgrammableVideoPlugin
      ios:
        pluginClass: TwilioProgrammableVideoPlugin
      web:
        default_package: twilio_programmable_video_web
