# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - unnecessary_brace_in_string_interps
    - non_constant_identifier_names
    - cancel_subscriptions

# analyzer:
#   exclude:
#     - path/to/excluded/files/**